name: Windows/MacOS

on: [push, pull_request]

jobs:
  cpu-extra:
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python-version: [3.9]
    steps:
      - name: Cancel previous run
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip setuptools wheel
      - name: Install dependencies
        run: |
          python -m pip install ".[dev]" --upgrade
          python -m pip uninstall ray -y
      - name: wandb login
        run: |
          wandb login e2366d661b89f2bee877c40bee15502d67b7abef
      - name: Test with pytest
        run: |
          pytest test/base test/continuous --cov=tianshou --durations=0 -v --color=yes
