name: PEP8, Types and Docs Check

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous run
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip setuptools wheel
      - name: Install dependencies
        run: |
          python -m pip install ".[dev]" --upgrade
      - name: Lint
        run: |
          python -m pip install pre-commit
          make lint
      - name: Type check
        run: |
          make mypy
      - name: Test spelling
        run: |
          make spelling
